version: 2.1

executors:
  default:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/caver-java-ext-kas

commands:
  notify-success:
    steps:
      - run:
          name: "notify slack when job success"
          command : |
            curl --data '{"text": "✅ Job *'$CIRCLE_JOB'* succeeded on *'$CIRCLE_BRANCH''$CIRCLE_TAG'*. Please see '$CIRCLE_BUILD_URL' for details."}' "$SLACK_WEBHOOK_URL"
          when: on_success
  notify-failure:
    steps:
      - run:
          name: "notify slack when job fail"
          command : |
            curl --data '{"text": "❌ Job *'$CIRCLE_JOB'* failed on *'$CIRCLE_BRANCH''$CIRCLE_TAG'*. Please see '$CIRCLE_BUILD_URL' for details."}' "$SLACK_WEBHOOK_URL"
          when: on_fail
  check_rc:
    steps:
      - run:
          name: Check RC
          command: |
            if [[ -n $CIRCLE_TAG ]]; then
              sed -i "s/version '.*'/version '${CIRCLE_TAG:1}'/" build.gradle
              sed -n '/version/p' build.gradle
            else
              echo "Not RC version"
            fi
jobs:
  unit_test:
    executor: default
    steps:
      - checkout
      - run: |
          ./gradlew clean
          ./gradlew test --debug

  build:
    executor: default
    steps:
      - checkout
      - check_rc
      - run: ./gradlew build -x test --debug
      - persist_to_workspace:
          root: ~/caver-java-ext-kas
          paths:
            - build/*
      - store_artifacts:
          path: ./build

  tag_verify:
    executor: default
    steps:
      - checkout
      - run:
          name: "Verify tag and file verison match"
          command: ./.circleci/scripts/tag_verify.sh

  publish:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/caver-java-ext-kas
      - check_rc
      - run:
          name: "publish"
          command: |
              ./gradlew bintrayUpload --stacktrace --debug
      - notify-failure
      - notify-success

  release_PR:
    executor: default
    steps:
      - add_ssh_keys 
      - checkout
      - run:
          name: "Push release branch"
          command: |
              set -x
              echo "push to release branch: /release/${CIRCLE_TAG%-*}"
              git checkout -b release/${CIRCLE_TAG%-*}
              git push origin release/${CIRCLE_TAG%-*}
      - run:
          name: "Make PR to master branch"
          command: ./.circleci/scripts/release_pr.sh

  tagging:
    executor: default
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "Tagging and delete release branch"
          command: ./.circleci/scripts/release_tag_branch.sh

stage_defaults:
  default: &stage_default
    filters:
      tags:
        only:
          - /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.*/
          - /^v[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+.*/
      branches:
        ignore: 
          - /release\/.*/
  qa: &stage_qa
    filters:
      tags:
        only:
          - /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.*/
          - /^v[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+.*/
      branches:
        ignore: /.*/
  rc: &stage_rc
    filters:
      tags:
        only: /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.*/
      branches:
        ignore: /.*/
  tests: &test_steps
    requires:
      # - unit_test
      - tag_verify
      - build

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_test:
          <<: *stage_default
      - build:
          <<: *stage_default

      # publish jobs - rc
      - tag_verify:
          <<: *stage_qa
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.*/
            branches:
              ignore: /.*/

      - publish:
          <<: *stage_qa
          <<: *test_steps
          name: publish_rc

      - release_PR:
          <<: *stage_rc
          requires:
            - publish_rc

      # publish jobs - prod
      - publish:
          name: publish_prod
          filters:
            branches:
              only: master
      
      - tagging:
          requires:
            - publish_prod
